### PR TITLE
Add expiry for tokens

### PR DESCRIPTION
**Pull request by lauraannwilliams**
adds a configuration value and check for expired tokens, to create auth tokens that expire at a custom time

### CODE REVIEW

**Comment by baschtl** [comment]
Hey @lauraannwilliams,

thanks a lot for providing this PR! Great!

Could you have a look at the failing specs on Travis and add some information to the readme about the new configuration option?

**Comment by baschtl** [comment]
@lauraannwilliams Isn't this the same functionality as the devise timeoutable module (http://www.rubydoc.info/github/plataformatec/devise/master/Devise/Models/Timeoutable) gives us?

**Comment by mikwat** [comment]
I actually think this would be a good improvement. The devise timeoutable module doesn't quite accomplish the same thing. Timeoutable will invalidate a session after a period of inactivity, but if you include the same auth token in every request, a new session will be created each time and thus the token will never be reset.

**Comment by mikwat** [comment]
@baschtl I've resurrected this PR (and fixed the specs) https://github.com/baschtl/devise-token_authenticatable/compare/v0.4.6...TetrationAnalytics:v0.4.7 but since there isn't a branch for v0.4.6 I can't submit a PR.

**Comment by baschtl** [comment]
Changes were incorporated in version [0.4.9](https://rubygems.org/gems/devise-token_authenticatable/versions/0.4.9). Thanks @lauraannwilliams !

**Comment by leonelgalan** [comment]
Does the introduction of this PR requires a `authentication_token_created_at` on the users table? I'm haven't change any setting, other than upgrading the gem and I'm getting:

`NoMethodError: undefined method `authentication_token_created_at=' for #<User:0x007f4eff0fb388>`

```
…ctivemodel-4.2.6/lib/active_model/attribute_methods.rb: 433:in `method_missing'
…atable-0.5.0/lib/devise/token_authenticatable/model.rb:  62:in `reset_authentication_token'
…atable-0.5.0/lib/devise/token_authenticatable/model.rb:  73:in `ensure_authentication_token'
/app/app/controllers/api/v2/registrations_controller.rb:  17:in `create'
```

**Comment by mikwat** [comment]
Yes @leonelgalan See here:
https://github.com/baschtl/devise-token_authenticatable/releases/tag/v0.4.9

Should we make it so this field isn't required, @baschtl ?

**Comment by leonelgalan** [comment]
I missed there. Specially being a 0.0.x increase, I didn't expect breaking changes. My gut says yes, as long as the setting is optional and off by default the field should too. I'll take a look.

**Comment by baschtl** [comment]
@mikwat Yes, optional would be good. I just did not have the time to reason about it.

@leonelgalan Thanks for the input. You are also welcome to improve the readme via a pull request. :-)

**Comment by mikwat** [comment]
@baschtl Here's a fix (if you create a branch for 0.4.9 I can send a proper PR): https://github.com/baschtl/devise-token_authenticatable/compare/v0.4.9...TetrationAnalytics:optional-token-expires-in

CC: @leonelgalan

**Comment by mikwat** [comment]
Specs are passing: https://travis-ci.org/TetrationAnalytics/devise-token_authenticatable/builds/138157233

**Comment by baschtl** [comment]
@mikwat See https://github.com/baschtl/devise-token_authenticatable/tree/v0.4.9.

**Pull request closed without merging**
