### PR TITLE
extend version support for devise 4.0.0

### PR DESCRIPTION
**Pull request by koenpunt**
This to support Rails 5.

I'm already running this for a few days without problems.

`expire_authentication_token_on_timeout` was deprecated in Devise 3.5.2, which causes the tests to fail, don't know if this is functionality that has to reimplemented, or can be removed altogether.

### CODE REVIEW

**Comment by baschtl** [comment]
@koenpunt Hey, thanks a lot for your contribution and the hint concerning `expire_auth_token_on_timeout`. I am currently working on a backport of it and hope to create a new release in the next couple of days.

**Comment by koenpunt** [comment]
I've pulled in the changes from master, and the tests almost pass. I guess because Devise 4 requires Ruby 2 the the first one fails. Not sure about jruby

**Comment by baschtl** [comment]
Hey @koenpunt,

try out https://github.com/baschtl/devise-token_authenticatable/tree/v0.5.0.beta. Also released on rubygems: https://rubygems.org/gems/devise-token_authenticatable/versions/0.5.0.beta.

Cheers.

**Comment by koenpunt** [comment]
Cool, thanks!

**Comment by leonelgalan** [comment]
Hey @baschtl, I've been on the beta for a while, seems to work. Do you plan to release it soon (non-beta) and would you relax the device version to 4.x? Currently the dependency is satisfied with 4.0.x, but devise is already on 4.1.x and moving forward I suppose.

**Comment by baschtl** [comment]
Hi @leonelgalan, sorry for the late reply - holidays. ;-)

I will try to work on it this week. Thanks for the hint!

**Comment by baschtl** [comment]
I released versions 0.4.9 and 0.5.0, yesterday. Please, have a look at the [release notes](https://github.com/baschtl/devise-token_authenticatable/releases) for both versions prior to upgrading.

**Pull request closed without merging**
